#!/bin/bash

set -euo pipefail

if [ $# -ne 3 ]; then
    echo "Usage: $0 <service> <domain> <port>"
    exit 1
fi

SERVICE="$1"
DOMAIN="$2"
PORT="$3"

TARGET="/etc/nginx/sites-available/$SERVICE.conf"

export DOMAIN PORT
envsubst '${DOMAIN} ${PORT}' <<'EOF' | sudo tee "$TARGET" > /dev/null
server {
    server_name $DOMAIN.moraviel.dev;

    include snippets/errors.conf;

    location / {
        proxy_pass http://localhost:$PORT;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
    }
}
EOF

echo "Created $TARGET"
